Repository andmecsan/Acme-Courses-22.8, pull requests merged in 2022-11, with the labels that each got.

#36 Task-015: Done
  src/main/java/acme/features/authenticated/consumer/AuthenticatedConsumerController.java
  src/main/java/acme/features/authenticated/consumer/AuthenticatedConsumerCreateService.java
  src/main/java/acme/features/authenticated/consumer/AuthenticatedConsumerRepository.java
  src/main/java/acme/features/authenticated/consumer/AuthenticatedConsumerUpdateService.java
  src/main/java/acme/features/authenticated/provider/AuthenticatedProviderController.java
  src/main/java/acme/features/authenticated/provider/AuthenticatedProviderCreateService.java
  src/main/java/acme/features/authenticated/provider/AuthenticatedProviderRepository.java
  src/main/java/acme/features/authenticated/provider/AuthenticatedProviderUpdateService.java
  src/main/java/acme/roles/Consumer.java
  src/main/java/acme/roles/Learner.java
  src/main/java/acme/roles/Provider.java
  src/main/java/acme/roles/Teacher.java
  src/main/webapp/WEB-INF/views/authenticated/consumer/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/consumer/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/consumer/messsages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/provider/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/provider/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/provider/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, second deliverable

#37 Task-016:Done
  src/main/java/acme/entities/blinks/Blink.java
Labels: enhancement, second deliverable

#39 Task-017:Done
  src/main/java/acme/entities/posts/Post.java
Labels: enhancement, second deliverable

#40 Task-018: Done
  src/main/java/acme/entities/tutorials/Tutorial.java
  src/main/java/acme/entities/tutorials/TutorialType.java
Labels: enhancement, second deliverable

#41 Task-021: Done
  src/main/java/acme/entities/help_requests/HelpRequest.java
  src/main/java/acme/entities/help_requests/HelpRequestStatus.java
Labels: enhancement, second deliverable

#42 Task 020: Done
  src/main/java/acme/entities/courses/Course.java
  src/main/java/acme/entities/quantities/Quantity.java
Labels: enhancement, second deliverable

#43 Task 22: Done
  src/main/java/acme/entities/follow_up/FollowUp.java
Labels: enhancement, second deliverable

#44 Task-028: Done
  src/main/java/acme/entities/tutorials/Tutorial.java
  src/main/webapp/WEB-INF/resources/initial-data/user-account.csv
  src/main/webapp/WEB-INF/resources/sample-data/blink.csv
  src/main/webapp/WEB-INF/resources/sample-data/consumer.csv
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
  src/main/webapp/WEB-INF/resources/sample-data/followUp.csv
  src/main/webapp/WEB-INF/resources/sample-data/helpRequest.csv
  src/main/webapp/WEB-INF/resources/sample-data/learner.csv
  src/main/webapp/WEB-INF/resources/sample-data/post.csv
  src/main/webapp/WEB-INF/resources/sample-data/provider.csv
  src/main/webapp/WEB-INF/resources/sample-data/quantity.csv
  src/main/webapp/WEB-INF/resources/sample-data/teacher.csv
  src/main/webapp/WEB-INF/resources/sample-data/tutorial.csv
Labels: enhancement, second deliverable

#45 Task-023: Done
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardRepository.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
  src/main/java/acme/forms/AdministratorDashboard.java
Labels: enhancement, second deliverable

#73 Hotfix
  reports/D01/Planning report.docx
  reports/D01/Planning report.pdf
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardRepository.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
Labels: bug

#48 Task 026: Done
  reports/model.uxf
Labels: documentation, second deliverable

#49 Reports: Done
  reports/D02/Planning report.docx
  reports/D02/Planning report.pdf
  reports/D02/Progress report.docx
  reports/D02/Progress report.pdf
  reports/D02/~$ogress report.docx
Labels: documentation, second deliverable

#47 Task 024: Done
  src/main/java/acme/entities/systemConfigurations/SystemConfiguration.java
  src/main/webapp/WEB-INF/resources/initial-data/system-configuration.csv
Labels: enhancement, second deliverable

#78 Project properties and pom have been fixerd
  .project
  .settings/org.eclipse.wst.common.component
  pom.xml
Labels: bug

#79 Changes pre-release
  reports/model.uxf
  src/main/java/acme/entities/tutorials/Tutorial.java
Labels: bug

#80 CSV has been fixed
  src/main/webapp/WEB-INF/resources/sample-data/tutorial.csv
Labels: bug

#92 Task-030: Done
  src/main/java/acme/features/any/userAccounts/AnyUserAccountsController.java
  src/main/java/acme/features/any/userAccounts/AnyUserAccountsListService.java
  src/main/java/acme/features/any/userAccounts/AnyUserAccountsRepository.java
  src/main/java/acme/features/any/userAccounts/AnyUserAccountsShowService.java
  src/main/webapp/WEB-INF/views/any/user-account/form.jsp
  src/main/webapp/WEB-INF/views/any/user-account/list.jsp
  src/main/webapp/WEB-INF/views/any/user-account/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/user-account/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#74 Task 31: Done
  src/main/java/acme/features/any/blink/AnyBlinkController.java
  src/main/java/acme/features/any/blink/AnyBlinkListService.java
  src/main/java/acme/features/any/blink/AnyBlinkRepository.java
  src/main/webapp/WEB-INF/views/any/blink/list.jsp
  src/main/webapp/WEB-INF/views/any/blink/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/blink/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#76 Task 32 and 33: Done
  src/main/java/acme/features/any/tutorials/AnyLabTutorialListService.java
  src/main/java/acme/features/any/tutorials/AnyTheoryTutorialListService.java
  src/main/java/acme/features/any/tutorials/AnyTutorialController.java
  src/main/java/acme/features/any/tutorials/AnyTutorialRepository.java
  src/main/java/acme/features/any/tutorials/AnyTutorialShowService.java
  src/main/webapp/WEB-INF/views/any/tutorial/form.jsp
  src/main/webapp/WEB-INF/views/any/tutorial/list.jsp
  src/main/webapp/WEB-INF/views/any/tutorial/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/tutorial/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#77 Task 034: Done
  src/main/java/acme/entities/courses/Course.java
  src/main/java/acme/features/any/courses/AnyCourseController.java
  src/main/java/acme/features/any/courses/AnyCourseListService.java
  src/main/java/acme/features/any/courses/AnyCourseListWithTutorialService.java
  src/main/java/acme/features/any/courses/AnyCourseRepository.java
  src/main/java/acme/features/any/courses/AnyCourseShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
  src/main/webapp/WEB-INF/views/any/course/form.jsp
  src/main/webapp/WEB-INF/views/any/course/list.jsp
  src/main/webapp/WEB-INF/views/any/course/messsages-en.i18n
  src/main/webapp/WEB-INF/views/any/course/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#86 Task 035: Done
  src/main/java/acme/features/authenticated/posts/AuthenticatedPostController.java
  src/main/java/acme/features/authenticated/posts/AuthenticatedPostListService.java
  src/main/java/acme/features/authenticated/posts/AuthenticatedPostRepository.java
  src/main/java/acme/features/authenticated/posts/AuthenticatedPostShowService.java
  src/main/webapp/WEB-INF/views/authenticated/post/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/post/list.jsp
  src/main/webapp/WEB-INF/views/authenticated/post/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/post/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#87 Task 036: Done
  src/main/java/acme/features/authenticated/systemConfigurations/AuthenticatedSystemConfigController.java
  src/main/java/acme/features/authenticated/systemConfigurations/AuthenticatedSystemConfigRepository.java
  src/main/java/acme/features/authenticated/systemConfigurations/AuthenticatedSystemConfigShowService.java
  src/main/webapp/WEB-INF/views/authenticated/system-configuration/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/system-configuration/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/system-configuration/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#89 Task-037/38: Done
  src/main/java/acme/entities/courses/Course.java
  src/main/java/acme/features/teacher/tutorials/TeacherLabListService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTheoryListService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialController.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialRepository.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/teacher/tutorial/form.jsp
  src/main/webapp/WEB-INF/views/teacher/tutorial/list.jsp
  src/main/webapp/WEB-INF/views/teacher/tutorial/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/tutorial/messages-es.i18n
Labels: enhancement, third deliverable

#84 Task 040: Done
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestController.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestListService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestRepository.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/teacher/help-request/form.jsp
  src/main/webapp/WEB-INF/views/teacher/help-request/list.jsp
  src/main/webapp/WEB-INF/views/teacher/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/help-request/messsages-es.i18n
Labels: enhancement, third deliverable

#85 Task 042: Done
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestController.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestListService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestRepository.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/form.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/list.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/learner/help-request/messsages-es.i18n
Labels: enhancement, third deliverable

#91 Task-044: Done
  src/main/java/acme/features/learner/dashboard/LearnerDashboardController.java
  src/main/java/acme/features/learner/dashboard/LearnerDashboardRepository.java
  src/main/java/acme/features/learner/dashboard/LearnerDashboardShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/learner/learner-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/learner/learner-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/learner/learner-dashboard/messages-es.i18n
Labels: enhancement, third deliverable

#90 Task 045: Done
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigController.java
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigRepository.java
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigShowService.java
  src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#82 Task-046: Done
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardRepository.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/blink.csv
  src/main/webapp/WEB-INF/resources/sample-data/helpRequest.csv
  src/main/webapp/WEB-INF/resources/sample-data/post.csv
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/administrator-dashboard/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, third deliverable

#93 Fixed Task 39 and minor bugs
  src/main/java/acme/entities/courses/Course.java
  src/main/java/acme/features/teacher/tutorials/TeacherLabListService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTheoryListService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialController.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialRepository.java
  src/main/webapp/WEB-INF/resources/sample-data/tutorial.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
Labels: bug, third deliverable

#116 Hotfix: Fixed bad smell
  src/main/java/acme/features/any/userAccounts/AnyUserAccountsListService.java
Labels: bug

#121 hotfix: fix missing field system configuration
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigShowService.java
  src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-es.i18n
Labels: bug, third deliverable

#120 hotfix: fix the documents
  reports/D02/Planning report.docx
  reports/D02/Planning report.pdf
  reports/D02/Progress report.docx
  reports/D02/Progress report.pdf
Labels: documentation, second deliverable

#117 Task-048/052: Done
  reports/D03/Lint report.docx
  reports/D03/Lint report.pdf
  reports/D03/Performance report.docx
  reports/D03/Performance report.pdf
  reports/D03/Planning report.docx
  reports/D03/Planning report.pdf
  reports/D03/Progress report.docx
  reports/D03/Progress report.pdf
  reports/D03/~$nt report.docx
  reports/D03/~$rformance report.docx
Labels: documentation, third deliverable

#118 Task-053: Done
  src/main/java/acme/features/authenticated/learner/AuthenticatedLearnerController.java
  src/main/java/acme/features/authenticated/learner/AuthenticatedLearnerCreateService.java
  src/main/java/acme/features/authenticated/learner/AuthenticatedLearnerRepository.java
  src/main/java/acme/features/authenticated/teacher/AuthenticatedTeacherController.java
  src/main/java/acme/features/authenticated/teacher/AuthenticatedTeacherCreateService.java
  src/main/java/acme/features/authenticated/teacher/AuthenticatedTeacherRepository.java
  src/main/webapp/WEB-INF/views/authenticated/learner/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/learner/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/learner/messages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/teacher/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/teacher/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/teacher/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Fourth deliverable

#124 Task-059: Done
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestAcceptService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestController.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestDenyService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestShowService.java
  src/main/webapp/WEB-INF/views/teacher/help-request/form.jsp
  src/main/webapp/WEB-INF/views/teacher/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/help-request/messsages-es.i18n
Labels: enhancement, Fourth deliverable

#125 Task 060: Done
  external/spamFilter.jar
  src/main/java/acme/features/teacher/follow_up/TeacherFollowUpController.java
  src/main/java/acme/features/teacher/follow_up/TeacherFollowUpCreateService.java
  src/main/java/acme/features/teacher/follow_up/TeacherFollowUpRepository.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestShowService.java
  src/main/java/acme/utils/SpamFilterService.java
  src/main/webapp/WEB-INF/resources/initial-data/system-configuration.csv
  src/main/webapp/WEB-INF/views/teacher/follow-up/form.jsp
  src/main/webapp/WEB-INF/views/teacher/follow-up/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/follow-up/messsages-es.i18n
  src/main/webapp/WEB-INF/views/teacher/help-request/form.jsp
  src/main/webapp/WEB-INF/views/teacher/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/help-request/messsages-es.i18n
Labels: enhancement, Fourth deliverable

#127 Task-061: Done
  src/main/java/acme/entities/help_requests/HelpRequest.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestController.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestCreateService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestDeleteService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestPublishService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestRepository.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestShowService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestUpdateService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestAcceptService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestDenyService.java
  src/main/java/acme/features/teacher/help_request/TeacherHelpRequestRepository.java
  src/main/webapp/WEB-INF/resources/sample-data/helpRequest.csv
  src/main/webapp/WEB-INF/views/learner/help-request/form.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/list.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/learner/help-request/messsages-es.i18n
Labels: enhancement, Fourth deliverable

#130 Task-063: Done
  src/main/java/acme/features/administrator/posts/AdministratorPostController.java
  src/main/java/acme/features/administrator/posts/AdministratorPostCreateService.java
  src/main/java/acme/features/administrator/posts/AdministratorPostRepository.java
  src/main/webapp/WEB-INF/views/administrator/post/form.jsp
  src/main/webapp/WEB-INF/views/administrator/post/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/post/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Fourth deliverable

#131 Task-064: Done
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigController.java
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigRepository.java
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigurationUpdateService.java
  src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/system-configuration/messsages-es.i18n
Labels: enhancement, Fourth deliverable

#126 Task 062: Done
  src/main/java/acme/features/learner/follow_up/LearnerFollowUpController.java
  src/main/java/acme/features/learner/follow_up/LearnerFollowUpCreateService.java
  src/main/java/acme/features/learner/follow_up/LearnerFollowUpRepository.java
  src/main/webapp/WEB-INF/views/learner/follow-up/form.jsp
  src/main/webapp/WEB-INF/views/learner/follow-up/messages-en.i18n
  src/main/webapp/WEB-INF/views/learner/follow-up/messsages-es.i18n
  src/main/webapp/WEB-INF/views/learner/help-request/form.jsp
  src/main/webapp/WEB-INF/views/learner/help-request/messages-en.i18n
  src/main/webapp/WEB-INF/views/learner/help-request/messsages-es.i18n
Labels: enhancement, Fourth deliverable

#129 Task 056/057: Done
  src/main/java/acme/entities/tutorials/Tutorial.java
  src/main/java/acme/features/teacher/tutorials/TeacherLabCreateService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTheoryCreateService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialController.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialDeleteService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialPublishService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialRepository.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialShowService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialUpdateService.java
  src/main/webapp/WEB-INF/resources/sample-data/tutorial.csv
  src/main/webapp/WEB-INF/views/teacher/tutorial/form.jsp
  src/main/webapp/WEB-INF/views/teacher/tutorial/list.jsp
  src/main/webapp/WEB-INF/views/teacher/tutorial/messages-en.i18n
  src/main/webapp/WEB-INF/views/teacher/tutorial/messages-es.i18n
Labels: enhancement, Fourth deliverable

#135 Fixed severals warnings
  src/main/java/acme/features/administrator/posts/AdministratorPostCreateService.java
  src/main/java/acme/features/administrator/systemConfigurations/AdministratorSystemConfigurationUpdateService.java
  src/main/java/acme/features/learner/follow_up/LearnerFollowUpCreateService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestCreateService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestDeleteService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestPublishService.java
  src/main/java/acme/features/learner/help_request/LearnerHelpRequestUpdateService.java
  src/main/java/acme/features/teacher/courses/TeacherCoursePublishService.java
  src/main/java/acme/features/teacher/courses/TeacherCourseUpdateService.java
  src/main/java/acme/features/teacher/quantity/TeacherQuantityDeleteService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialDeleteService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialPublishService.java
  src/main/java/acme/features/teacher/tutorials/TeacherTutorialUpdateService.java
  src/main/java/acme/utils/SpamFilterService.java
  src/main/webapp/WEB-INF/views/authenticated/learner/messages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/teacher/messages-es.i18n
  src/main/webapp/WEB-INF/views/learner/help-request/form.jsp
Labels: bug
